---
languageCode: id-ina
baseUrl: ''
title: Catatan Guru Honorer
theme: anubis
paginate: 10
disqusShortname: hermancahyono
googleAnalytics: G-12345
enableRobotsTXT: true
menu:
  main:
  - url: "/post/RPL/"
    name: RPL
    weight: 2
  - url: "/post/"
    name: Arsip
    title: Archive
    weight: 1
    identifier: archive
params:
  author: Herman Cahyono
  email: herman.btu@gmail.com
  avatar: "/images/me.png"
  description: ''
  dateFormat: '2006-01-02'
  paginationSinglePost: true
  style: dark-without-switcher
  readMore: false
  disableSummary: false
  utterancesRepo: ''
  utterancesTheme: ''
  utterancesIssue: ''
  utterancesLabel: ''
  isso:
    enabled: true
    data: https://comments.example.com/
    jsLocation: https://comments.example.com/js/embed.min.js
    css: true
    lang: de
    replyToSelf: true
    requireAuthor: true
    requireEmail: true
    id: thread-id
    avatar: true
    avatar-bg: "#f0f0f0"
  webmentions:
    url: https://yourdomain.com/webemntions/receive
    login: hugo-theme-anubis
    pingback: true
  social:
  - id: github
    name: hermanch
markup:
  goldmark:
    renderer:
      unsafe: true
